module.exports = {
    PORT: 5500,
    ACCESS_KEY_ID: "AKIA6ODU5QN3XYEE55ET",
    SECRET_ACCESS_KEY: "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",
    AWS_REGION: "ap-south-1",
    BUCKET1: "staykarhotelimage",
    BUCKET2: "staykarinvoicesbucket",
    BUCKET3:'testbucketinstyker',
    JWT_PRIVATE_KEY: "staykrhaider@1344",
    USERMAIL: "staykr1@outlook.com",
    USERPASS: "Time@123!@#",
    RAZOR_PAY_KEY_ID: "rzp_test_1lU5GmvhNpeBuf",
    RAZOR_PAY_KEY_SECRATE: "6vGnG7PORo7C1Xh397vUD0dT",
    RAZOR_PAY_WEBHOOK_SECRATE: "Time@123!@#",
    SMPT_MAIL: "saifjava2@gmail.com",
    SMPT_PASSWORD: "hyzcsbbodglsntrr",
    SMPT_SERVICE: "gamil",
    SMPT_HOST: "smtp.gmail.com",
    SMPT_PORT: 465,
  };